module.exports = {
  TemperaturaBusiness: require("./temperatura.business"),
  NubosidadBusiness: require("./nubosidad.business"),
  VisibilidadBusiness: require("./visibilidad.business"),
  TermometroSecoBusiness: require("./termometro-seco.business"),
  TermometroHumedoBusiness: require("./termometro-humedo.business"),
  GeotermometroBusiness: require("./geotermometro.business"),
  DireccionVientoBusiness: require("./direccion-viento.business"),
  PresionAtmosfericaBusiness: require("./presion-atmosferica.business"),
  RegistroBusiness: require("./registro.business"),
  UsuarioBusiness: require("./usuario.business"),
  TemperaturaJournalBusiness: require("./temperatura-journal.business"),
  NubosidadJournalBusiness: require("./nubosidad-journal.business"),
  VisibilidadJournalBusiness: require("./visibilidad-journal.business"),
  TermometroSecoJournalBusiness: require("./termometro-seco-journal.business"),
  TermometroHumedoJournalBusiness: require("./termometro-humedo-journal.business"),
  GeotermometroJournalBusiness: require("./geotermometro-journal.business"),
  DireccionVientoJournalBusiness: require("./direccion-viento-journal.business"),
  PresionAtmosfericaJournalBusiness: require("./presion-atmosferica-journal.business"),
  RegistroJournalBusiness: require("./registro-journal.business"),
  UsuarioJournalBusiness: require("./usuario-journal.business"),
};
