module.exports = {
  TemperaturaService: require("./temperatura.service"),
  NubosidadService: require("./nubosidad.service"),
  VisibilidadService: require("./visibilidad.service"),
  TermometroSecoService: require("./termometro-seco.service"),
  TermometroHumedoService: require("./termometro-humedo.service"),
  GeotermometroService: require("./geotermometro.service"),
  DireccionVientoService: require("./direccion-viento.service"),
  PresionAtmosfericaService: require("./presion-atmosferica.service"),
  RegistroService: require("./registro.service"),
  UsuarioService: require("./usuario.service"),
  TemperaturaJournalService: require("./temperatura-journal.service"),
  NubosidadJournalService: require("./nubosidad-journal.service"),
  VisibilidadJournalService: require("./visibilidad-journal.service"),
  TermometroSecoJournalService: require("./termometro-seco-journal.service"),
  TermometroHumedoJournalService: require("./termometro-humedo-journal.service"),
  GeotermometroJournalService: require("./geotermometro-journal.service"),
  DireccionVientoJournalService: require("./direccion-viento-journal.service"),
  PresionAtmosfericaJournalService: require("./presion-atmosferica-journal.service"),
  RegistroJournalService: require("./registro-journal.service"),
  UsuarioJournalService: require("./usuario-journal.service"),
};
