module.exports = {
  TemperaturaDto: require("./temperatura.dto"),
  NubosidadDto: require("./nubosidad.dto"),
  VisibilidadDto: require("./visibilidad.dto"),
  TermometroSecoDto: require("./termometro-seco.dto"),
  TermometroHumedoDto: require("./termometro-humedo.dto"),
  GeotermometroDto: require("./geotermometro.dto"),
  DireccionVientoDto: require("./direccion-viento.dto"),
  PresionAtmosfericaDto: require("./presion-atmosferica.dto"),
  RegistroDto: require("./registro.dto"),
  PermisoDto: require("./permiso.dto"),
  UsuarioPermisoDto: require("./usuario-permiso.dto"),
  Registro2Dto: require("./registro2.dto"),
  TemperaturaJournalDto: require("./temperatura-journal.dto"),
  NubosidadJournalDto: require("./nubosidad-journal.dto"),
  VisibilidadJournalDto: require("./visibilidad-journal.dto"),
  TermometroSecoJournalDto: require("./termometro-seco-journal.dto"),
  TermometroHumedoJournalDto: require("./termometro-humedo-journal.dto"),
  GeotermometroJournalDto: require("./geotermometro-journal.dto"),
  DireccionVientoJournalDto: require("./direccion-viento-journal.dto"),
  PresionAtmosfericaJournalDto: require("./presion-atmosferica-journal.dto"),
  RegistroJournalDto: require("./registro-journal.dto"),
};
