module.exports = {
  TemperaturaRepository: require("./temperatura.repository"),
  NubosidadRepository: require("./nubosidad.repository"),
  VisibilidadRepository: require("./visibilidad.repository"),
  TermometroSecoRepository: require("./termometro-seco.repository"),
  TermometroHumedoRepository: require("./termometro-humedo.repository"),
  GeotermometroRepository: require("./geotermometro.repository"),
  DireccionVientoRepository: require("./direccion-viento.repository"),
  PresionAtmosfericaRepository: require("./presion-atmosferica.repository"),
  RegistroRepository: require("./registro.repository"),
  UsuarioRepository: require("./usuario.repository"),
  PermisoRepository: require("./permiso-repository"),
  UsuarioPermisoRepository: require("./usuario-permiso.repository"),
  TemperaturaJournalRepository: require("./temperatura-journal.repository"),
  NubosidadJournalRepository: require("./nubosidad-journal.repository"),
  VisibilidadJournalRepository: require("./visibilidad-journal.repository"),
  TermometroSecoJournalRepository: require("./termometro-seco-journal.repository"),
  TermometroHumedoJournalRepository: require("./termometro-humedo-journal.repository"),
  GeotermometroJournalRepository: require("./geotermometro-journal.repository"),
  DireccionVientoJournalRepository: require("./direccion-viento-journal.repository"),
  PresionAtmosfericaJournalRepository: require("./presion-atmosferica-journal.repository"),
  RegistroJournalRepository: require("./registro-journal.repository"),
  UsuarioJournalRepository: require("./usuario-journal.repository"),
};
