module.exports = {
  Temperatura: require("./temperatura"),
  Nubosidad: require("./nubosidad"),
  Visibilidad: require("./visibilidad"),
  TermometroSeco: require("./termometro-seco"),
  TermometroHumedo: require("./termometro-humedo"),
  Geotermometro: require("./geotermometro"),
  DireccionViento: require("./direccion-viento"),
  PresionAtmosferica: require("./presion-atmosferica"),
  Registro: require("./registro"),
  Usuario: require("./usuario"),
  TemperaturaJournal: require("./temperatura-journal"),
  NubosidadJournal: require("./nubosidad-journal"),
  VisibilidadJournal: require("./visibilidad-journal"),
  TermometroSecoJournal: require("./termometro-seco-journal"),
  TermometroHumedoJournal: require("./termometro-humedo-journal"),
  GeotermometroJournal: require("./geotermometro-journal"),
  DireccionVientoJournal: require("./direccion-viento-journal"),
  PresionAtmosfericaJournal: require("./presion-atmosferica-journal"),
  RegistroJournal: require("./registro-journal"),
  UsuarioJournal: require("./usuario-journal"),
};
